# Generated by Django 2.2 on 2020-06-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
