# Generated by Django 2.2 on 2020-07-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0003_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rated_by',
            field=models.ManyToManyField(related_name='raters', to='recipe_db.User'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe_db.Recipe')),
            ],
        ),
    ]
