# Generated by Django 2.2 on 2020-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0003_auto_20200613_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
