# Generated by Django 2.2 on 2020-07-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0004_auto_20200704_2151'),
        ('recipe_db', '0004_auto_20200706_2029'),
    ]

    operations = [
    ]
