# Generated by Django 2.2 on 2020-06-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0004_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_recipes', to='recipe_db.User'),
        ),
    ]
