# Generated by Django 2.2 on 2020-06-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0006_auto_20200614_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
