# Generated by Django 2.2 on 2020-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_db', '0007_auto_20200614_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
